## NumPy
 - **Array:** An array is a data type structure used to store multiple values of the same data type in single variable.

### NumPy
 - used for numerical computing.
 - It provides support for large, multi-dimensional arrays and matrices, along with a wide range of mathematical functions to operate on them efficiently.
 - Faster than Python lists for numerical operations.
 - Uses less memory.
 - (performing operations on entire arrays without loops.
 - Provides many mathematical, statistical, and linear algebra functions.

In [ ]:
#pip install numpy

In [3]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
mat=([1,2,3],[4,5,6],[7,8,9])
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
matrix=[[6,3,5,2],[4,3,2,5],[4,3,7,4],[3,3,4,7]]

In [16]:
print(len(matrix))

4


In [19]:
m=np.array(matrix)
print(m)

[[6 3 5 2]
 [4 3 2 5]
 [4 3 7 4]
 [3 3 4 7]]


In [21]:
m.shape #for checking dimension

(4, 4)

 - In array where we see stating and ending with [ ] signle square bracket that means one-dimensional array,if starting and ending [ [  ] ] means two-dim aaray,similarly 3-dim and so on.

In [23]:
#generating sequence

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(0,20,2)   #np.arange(start,stop,step(gap)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
np.linspace(0,5,7)   #.linspace(start,stop,how many numbers you want)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [36]:
np.linspace(0,7,75)

array([0.        , 0.09459459, 0.18918919, 0.28378378, 0.37837838,
       0.47297297, 0.56756757, 0.66216216, 0.75675676, 0.85135135,
       0.94594595, 1.04054054, 1.13513514, 1.22972973, 1.32432432,
       1.41891892, 1.51351351, 1.60810811, 1.7027027 , 1.7972973 ,
       1.89189189, 1.98648649, 2.08108108, 2.17567568, 2.27027027,
       2.36486486, 2.45945946, 2.55405405, 2.64864865, 2.74324324,
       2.83783784, 2.93243243, 3.02702703, 3.12162162, 3.21621622,
       3.31081081, 3.40540541, 3.5       , 3.59459459, 3.68918919,
       3.78378378, 3.87837838, 3.97297297, 4.06756757, 4.16216216,
       4.25675676, 4.35135135, 4.44594595, 4.54054054, 4.63513514,
       4.72972973, 4.82432432, 4.91891892, 5.01351351, 5.10810811,
       5.2027027 , 5.2972973 , 5.39189189, 5.48648649, 5.58108108,
       5.67567568, 5.77027027, 5.86486486, 5.95945946, 6.05405405,
       6.14864865, 6.24324324, 6.33783784, 6.43243243, 6.52702703,
       6.62162162, 6.71621622, 6.81081081, 6.90540541, 7.     

In [26]:
np.zeros([3]) #[ ] list

array([0., 0., 0.])

In [27]:
np.zeros((5))  #() tuple

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
#Identity matrix

np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [38]:
# Random numbers generate

np.random.rand(8)  #one-dim aaray

array([0.83787576, 0.51545721, 0.0745964 , 0.69938681, 0.44506022,
       0.46990535, 0.7969734 , 0.6108578 ])

In [39]:
np.random.rand(3,3)   #two dim array

array([[0.27723195, 0.61730412, 0.64528291],
       [0.04370827, 0.23837778, 0.65853367],
       [0.80792528, 0.54287785, 0.63205735]])