## Exersice(NumPy)

**Q1. Import NumPy as np.**

In [1]:
import numpy as np

**Q2. Create Arrary of 10 zeros.**

In [3]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Q3. Create Arrary of 10 ones.**

In [4]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


**Q4. Create Arrary of 10 fives.**

In [7]:
print(np.full(10,5))

[5 5 5 5 5 5 5 5 5 5]


**Q5. Create an array of the integers from 10 to 50.**

In [9]:
arr=np.arange(10,51)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


**Q6. Create an array of all even integers from 10 to 50.**

In [11]:
ar=np.arange(10,50,2)
print(ar)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


**Q7. Create a $3 \times 3$ matrix with values ranging from 0 to 8.**

In [12]:
m=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Q8. Create a $3 \times 3$ identity matrix.**

In [13]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Q9. Use NumPy to generate a random number between 0 to 1.**

In [22]:
np.random.rand(1)   #generate random numbers between 0 to 1

array([0.3269415])

**Q10. Use NUmPy to generate an array of 25 random numbers sampled from standard normal distribution.**

In [24]:
np.random.randn(25)

array([ 0.86296541, -1.17115852, -0.21164369,  0.03062968,  0.0558787 ,
       -0.53750749, -2.26071023, -0.07412828, -1.2179504 ,  1.45155339,
        0.04638987, -0.3543631 ,  0.15488101, -0.83387587, -0.85423528,
        0.26045248, -0.39935481,  0.17746457,  2.12143171, -1.40387207,
        0.47136111,  0.19770801, -0.54323737, -1.32537102, -0.84618881])

**Q11. Create a matrix $10\times10$; and its element vary 0.01 to 1.**

In [34]:
m=np.arange(0.01,1.01,0.01).reshape(10,10)
print(m)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


**Q12. Create an array of 20 linearly spaced point between 0 \& 1.**

In [37]:
print(np.linspace(0,1,20))

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


### NumPy Indexing & Selection

In [39]:
mat=np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


**Q13. Write code here that reproduce the output of the below**
$$
\begin{bmatrix}
12 & 13 & 14 & 15\\
17 & 18 & 19 & 20\\
22 & 23 & 24 & 25
\end{bmatrix}
$$

In [40]:
print(mat[2:,1:])

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


**Q14. Write code here that reproduce the output of the below** $$20$$

In [57]:
print(mat[3,4])

20


**Q15. Write code here that reproduce the output of the below** 
$$
\begin{bmatrix}
2\\
17\\
12
\end{bmatrix}
$$

In [58]:
print(mat[:,1:2][0:3,])

[[ 2]
 [ 7]
 [12]]


In [59]:
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


**Q16. Write code here that reproduce the output of the below**
$$
\begin{bmatrix}
21 & 22 & 23 & 24 & 25
\end{bmatrix}
$$

In [60]:
print(mat[4])

[21 22 23 24 25]


**Q17. Write code here that reproduce the output of the below**
$$
\begin{bmatrix}
16 & 17 & 18 & 19 & 20\\
21 & 22 & 23 & 24 & 25
\end{bmatrix}
$$

In [62]:
print(mat[3:])

[[16 17 18 19 20]
 [21 22 23 24 25]]
