## NumPy
 - **Array:** An array is a data type structure used to store multiple values of the same data type in single variable.

### NumPy
 - used for numerical computing.
 - It provides support for large, multi-dimensional arrays and matrices, along with a wide range of mathematical functions to operate on them efficiently.
 - Faster than Python lists for numerical operations.
 - Uses less memory.
 - (performing operations on entire arrays without loops.
 - Provides many mathematical, statistical, and linear algebra functions.

In [ ]:
#pip install numpy

In [2]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
mat=([1,2,3],[4,5,6],[7,8,9])
np.array(mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
matrix=[[6,3,5,2],[4,3,2,5],[4,3,7,4],[3,3,4,7]]

In [16]:
print(len(matrix))

4


In [19]:
m=np.array(matrix)
print(m)

[[6 3 5 2]
 [4 3 2 5]
 [4 3 7 4]
 [3 3 4 7]]


In [21]:
m.shape #for checking dimension

(4, 4)

 - In array where we see stating and ending with [ ] signle square bracket that means one-dimensional array,if starting and ending [ [  ] ] means two-dim aaray,similarly 3-dim and so on.

In [23]:
#generating sequence

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(0,20,2)   #np.arange(start,stop,step(gap)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [35]:
np.linspace(0,5,7)   #.linspace(start,stop,how many numbers you want)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [36]:
np.linspace(0,7,75)

array([0.        , 0.09459459, 0.18918919, 0.28378378, 0.37837838,
       0.47297297, 0.56756757, 0.66216216, 0.75675676, 0.85135135,
       0.94594595, 1.04054054, 1.13513514, 1.22972973, 1.32432432,
       1.41891892, 1.51351351, 1.60810811, 1.7027027 , 1.7972973 ,
       1.89189189, 1.98648649, 2.08108108, 2.17567568, 2.27027027,
       2.36486486, 2.45945946, 2.55405405, 2.64864865, 2.74324324,
       2.83783784, 2.93243243, 3.02702703, 3.12162162, 3.21621622,
       3.31081081, 3.40540541, 3.5       , 3.59459459, 3.68918919,
       3.78378378, 3.87837838, 3.97297297, 4.06756757, 4.16216216,
       4.25675676, 4.35135135, 4.44594595, 4.54054054, 4.63513514,
       4.72972973, 4.82432432, 4.91891892, 5.01351351, 5.10810811,
       5.2027027 , 5.2972973 , 5.39189189, 5.48648649, 5.58108108,
       5.67567568, 5.77027027, 5.86486486, 5.95945946, 6.05405405,
       6.14864865, 6.24324324, 6.33783784, 6.43243243, 6.52702703,
       6.62162162, 6.71621622, 6.81081081, 6.90540541, 7.     

In [26]:
np.zeros([3]) #[ ] list

array([0., 0., 0.])

In [27]:
np.zeros((5))  #() tuple

array([0., 0., 0., 0., 0.])

In [29]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [32]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
#Identity matrix

np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [38]:
# Random numbers generate
#np.random.rand( ) -uniform distribution and range is 0 to 1.

np.random.rand(8)  #one-dim aaray

array([0.83787576, 0.51545721, 0.0745964 , 0.69938681, 0.44506022,
       0.46990535, 0.7969734 , 0.6108578 ])

In [39]:
np.random.rand(3,3)   #two dim array

array([[0.27723195, 0.61730412, 0.64528291],
       [0.04370827, 0.23837778, 0.65853367],
       [0.80792528, 0.54287785, 0.63205735]])

In [3]:
#np.random.randn() -normal(gaussian)distribution with mean 0 and s.d 1
#its range any real numbers(mostly -3 to 3),it can genrated both values +ve & -ve.

np.random.randn(5)

array([-1.51831155,  2.31632967, -0.99874855, -0.35038037,  0.83686799])

In [4]:
np.random.randn(2,5)   #2-dim array

array([[ 0.34311645, -0.48063711, -1.73283469, -0.37562977, -0.36768364],
       [ 0.99581884, -1.71329821, -1.3608752 , -0.29493015, -0.01408409]])

In [5]:
np.random.randn(7,5,2)   #3-dim array

array([[[-7.82687063e-01, -1.10765026e+00],
        [ 6.50748635e-01,  2.76734434e+00],
        [-1.13213989e+00, -3.26771122e-01],
        [-9.93092631e-01, -9.72472087e-01],
        [-1.93000656e-01,  7.00518526e-01]],

       [[ 9.53682007e-02,  1.49089314e+00],
        [-1.51693428e+00, -1.87872741e+00],
        [-1.25627705e+00, -1.86355880e-01],
        [ 3.76668163e-01, -1.37748878e+00],
        [-9.80449715e-03,  8.40418029e-01]],

       [[ 2.12326575e-01,  5.73509783e-01],
        [-1.50790112e+00,  5.04724459e-01],
        [-5.65552645e-01, -1.89346367e+00],
        [ 1.43338217e+00, -6.96152652e-01],
        [-2.48471671e+00,  2.35231218e-01]],

       [[-3.51700280e-01, -1.62446936e+00],
        [-9.23858923e-01, -3.98796101e-01],
        [ 2.05693639e+00,  8.44336897e-01],
        [ 2.59919659e-03, -4.87262713e-01],
        [-1.17521802e+00,  1.45173127e+00]],

       [[-1.76871756e-01, -5.57354714e-02],
        [-6.72206491e-01, -9.24623457e-01],
        [ 7.53491915e-01

In [6]:
#np.random.randint(lower,upper,size)    lower-included,upper-excluded  
#it generate random integer between specific range

np.random.randint(2,10) 

8

In [8]:
int=np.random.randint(2,20,5)     #one-dim array
print(int)

[ 2 19  9 16  3]


In [11]:
two_dim=np.random.randint(2,10,(2,3))    #2-dim array

In [12]:
print(two_dim)

[[2 4 6]
 [8 3 7]]


In [13]:
dim3=np.random.randint(2,10,(2,3,4))    #3-dim array
print(dim3)

[[[5 3 8 5]
  [2 3 8 5]
  [3 9 8 7]]

 [[6 5 7 3]
  [4 3 9 5]
  [5 4 4 8]]]


In [18]:
np.random.seed(42)       #when we use .seed() than we get repeated values
rep=np.random.randint(5,15,6)
print(rep)

[11  8 12  9 11 14]


In [42]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [22]:
arr=np.arange(2,18)
print(arr)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [24]:
arr.shape    #.shape - for checking dim(shape)

(16,)

In [28]:
print(arr.reshape(4,4))    #.reshape(  ,  ) - for change dim or shape

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]


In [31]:
rnd=np.random.randint(3,18,9)
print(rnd)

[ 5  8  7  4 10 14 16  8  4]


In [32]:
print(rnd.max())    #check max value of array

16


In [34]:
print(rnd.min())    #check min value of array

4


In [35]:
print(rnd.argmax())   #check position(location) of max value of array

6


In [36]:
print(rnd.argmin())   ##check position(location) of value of array

3


In [38]:
from numpy.random import randint     #imports a function used to generate random integers or multi-dimensional arrays of integers from a discrete uniform distribution.

randint(5,46)

25

In [40]:
randint(7,75,5)

array([39, 64, 28, 55, 65], dtype=int32)

In [41]:
print(randint(1,75,75))

[42 60 15 62 62 47 62 51 55 64  3 51  7 21 73 39 18  4 60 14  9 53  2 60
 71 44  8 47 35 36 50  4  2  6 54  4 54 63 18 44 34 74 62 14 48 15 72 62
 40 53 24 26 60 41 29 15 45 65 71  9  1  8 63 11  8 35 35 33  5 41 28  7
 73 72 12]


In [45]:
print(randint(0,88,14))


[ 4 13 26  8 78 14 41 76 50 62 51  3 22 14]


# NumPy Indexing \& Selection

### Indexing: means accessing one or more elements from a NumPy array using their position (index).
### Selection: means choosing multiple elements using slicing, conditions, or fancy indexing.

In [2]:
import numpy as np

In [3]:
arr=np.arange(0,11)

In [4]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [6]:
print(arr[8])

8


In [7]:
print(arr[1:5])

[1 2 3 4]


In [12]:
print(arr[:6])

#or

# arr[0:6]

[0 1 2 3 4 5]


In [11]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
print(arr[-1])

10


In [17]:
arr[0:5]=100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [21]:
print(arr[0:8:2])     #arr[start:stop:step]

[100 100 100   6]


In [24]:
#Slicing


ar=np.arange(0,16)
print(ar)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [26]:
slice_of_ar=ar[0:8]
print(slice_of_ar)

[0 1 2 3 4 5 6 7]


In [27]:
slice_of_ar[:]=75

In [28]:
slice_of_ar

array([75, 75, 75, 75, 75, 75, 75, 75])

In [29]:
ar[::2]    #every second element

array([75, 75, 75, 75,  8, 10, 12, 14])

In [30]:
ar_copy=ar.copy()

In [31]:
ar_copy

array([75, 75, 75, 75, 75, 75, 75, 75,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
ar_copy[:]=100

In [33]:
ar_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100])

In [34]:
ar

array([75, 75, 75, 75, 75, 75, 75, 75,  8,  9, 10, 11, 12, 13, 14, 15])